# This descriptions will explicate how functions the options of the plugin, the proteccions, titles, sounds and more.
# Also you can revise the plugin pagine for more information!
lobby-point: 
# this save the spawn location.
  world: ""
  x:
  y:
  z:
  yaw:
  pitch:  
disable-build: true
# if is "true", the players can't build or break in the lobby, only if have the necessary permission. (custolobby.build)
disable-damage: true
# this cancel the damage for the players.
disable-hunger: true
# this deactive the hunger.
disable-weather: true
# the weathers on the world will be cancelled.
disable-entities: true
# not spawn more entities on the world.
disable-interact: true
# the players can't interact with the world or the objects.
build-titles: true
# will send a title message for the user.
build-actionbar: true
# will send a actionbar when the user join.
build-firework: true
# will be launch a firework if detect a player has joined.
give-speed: true
# the players recibe a potion effect. (Speed II)
reproduce-sound: true
# if is true, reproduce a sound specified for the player
send-motd: true
# this is the principal welcome message for the user
send-networks: true
# if this is "true", all social networks of server will be send to player
title:
# on this options, you can specify the velocity with the title is sended, manteins and disappears
  fadeIn: 5
  stay: 20
  fadeOut: 35
firework-power: 5
# this number represents the power of fireworks
sound: NOTE_PLING
# this sound is produced when the player has joined to server
sounds-to-flight: true
# if the player execute the command "/flight", will reproduce the sound
id: ENDERDRAGON_WINGS
# this is the type of sound will be reproduce