lobby-point: 
  world: ""
  x:
  y:
  z:
  yaw:
  pitch:  
disable-build: true
disable-damage: true
disable-hunger: true
disable-weather: true
disable-entities: true
disable-interact: true
build-titles: true
build-actionbar: true
build-firework: true
give-speed: true
reproduce-sound: true
send-motd: true
send-networks: true
title: 
  fadeIn: 5
  stay: 20
  fadeOut: 35
firework-power: 5
sound: NOTE_PLING