# here you can change options of the plugin, active or deactive the functions.
settings: 
  lobby-point: 
    world: ""
    x:
    y:
    z:
    yaw:
    pitch: 
# this section define the spawn of the server
  damage: false
# this disable the damage for entities.
  hunger: false
# disable the hunger for the players.
  build: false
# the players can't build or break on the lobby.
  weather: false
# storms will be defused
  entities: false
# this will clear any entity on the world. (Zombies, animals, etc)
  use-actionbar: true
# if is true, when the player join to server will be send a actionbar.
  use-titles: true
# if is true, when the player join, will be show a message on screen.
  use-subtitles: true
# if is true, when the player join will be show a second message on screen.
  use-sounds: true
# if is true, when the player join will be produce a sound on the player location.
  use-fireworks: true
# when the player join, will be launch fireworks.
  give-speed: true
# if this is true, when the player join to server, if have the permission "custolobby.speed", will be receive Speed II.
  give-bow: true
# if is true, when the player join, will be receive a bow, with this item, the player can teleport to any place on the lobby.
  use-motd: true
# if is true, when the player join, will be receive a big message. (MOTD)
  use-networks: true
# when the player join, will be receive all the social networks of server.
  bow-slot: 1
# on this slot the bow will be given to player.  
  bow-name: "&aTeleporter"
# this name will be receive the bow.
  sound-id: NOTE_PLING
# insert here the sound id.
  firework-power: 5
# this represents the power of fireworks to be launch.
  title:
# this section will depends of class "SubtitlePlayer" and "TitlePlayer", this config affect the two class.
    fadeIn: 5
    stay: 20
    fadeOut: 35