main: net.custolobby.plugin.CustoLobby
name: CustoLobby
version: 1.0.1
author: AISimple
softdepends: [PlaceholderAPI]
depends: [TitleAPI, ActionBarAPI]
permissions:
  custolobby.*:
    children:
      - custolobby.teleport
      - custolobby.build
      - custolobby.quit
      - custolobby.join
      - custolobby.chat
      - custolobby.vanish
      - custolobby.nick
      - custolobby.manager
      - custolobby.fly
      - custolobby.setlobby
      - custolobby.lobby
      - custolobby.gamemode
      - custolobby.filter.bypass
      - custolobby.blacklist.bypass
      - custolobby.fireworks
      
commands:
  tp:
    aliases: [teleport]
  vanish:
    aliases: [v, invisibility]
  nick:
    aliases: [name]
  custolobby: 
    aliases: [cl, clobby]
  fly:
    aliases: [flight]
  setlobby:
    aliases: [sethub, setspawn]
  lobby:
    aliases: [hub, spawn]
  gm:
    aliases: [gamemode]
  help:
    aliases: [h]